version: 2
jobs:
  test:
    docker:
      - image: gapsystem/gap-docker:latest
    working_directory: ~/.gap/pkg/FinGSetsForCAP
    steps:
      - checkout
      - run: |
          sudo apt update
          sudo apt dist-upgrade -y
          sudo apt install -y texlive-latex-extra texlive-science texlive-fonts-extra curl
          cd ..
          git clone --depth 1 https://github.com/gap-packages/AutoDoc.git
          git clone --depth 1 https://github.com/homalg-project/homalg_project.git
          git clone --depth 1 https://github.com/homalg-project/CAP_project.git
          git clone --depth 1 https://github.com/homalg-project/Toposes.git
          git clone --depth 1 https://github.com/homalg-project/FinSetsForCAP.git
          cd FinGSetsForCAP
          TERM=dumb make ci-test
          bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  commit:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          # 0:00 UTC = 1:00 CET = 2:00 CEST
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
